/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'aya' at '16/06/12 16:12' with Gradle 2.11
 *
 * @author aya, @date 16/06/12 16:12
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
